import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConfigureAmplifyClientSide from "@/app/amplify-cognito-config";
import { SidebarProvider } from "../components/ui/sidebar";
import QueryProvider from "../providers/queryProviders";
import { Toaster } from "sonner";
import {Provider} from "@radix-ui/react-tooltip";
import {store} from "../store";
import {ReduxProvider} from "../providers/reduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Legacy App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <ConfigureAmplifyClientSide />
        <ReduxProvider>
          <QueryProvider>
            <SidebarProvider>{children}</SidebarProvider>
          </QueryProvider>
          <Toaster position="bottom-right" richColors closeButton />
        </ReduxProvider>
      </body>
    </html>
  );
}
