const TITLE_DASHBOARD = "Dashboard";
const TITLE_CATEGORY = "Category";
const TITLE_SHIPPING = "Shipping";
const TITLE_STOCK = "Stock";
const TITLE_SUPPLIER = "Supplier";
const TITLE_PROFILE = "Profile";
const TITLE_BILLING = "Billing";
const TITLE_SETTINGS = "Settings";
const TITLE_EMAIL_NOTIFICATION = "Email Notification";
const TITLE_SHIPPING_PRESETS = "Shipping Presets";
const TITLE_INVENTORY_PRODUCTS = "Inventory Products";
const TITLE_INVENTORY_STOCK = "Inventory Stock Management";
const TITLE_INVENTORY_ORDERS = "All Purchase Orders";
const TITLE_INVENTORY_ORDERS_ADD = "New Purchase Orders";
const TITLE_INVENTORY_ORDERS_DETAILS = "Purchase Orders Details";
const TITLE_INVENTORY_SUPPLIERS = "Inventory Suppliers";
const TITLE_INVENTORY_PURCHASE_ORDERS = "All Purchase Orders";
const TITLE_INVENTORY_PURCHASE_ORDERS_ADD = "New Purchase Orders";
const TITLE_INVENTORY_PURCHASE_ORDERS_DETAILS = "Purchase Orders Details";
const TITLE_INVENTORY_TRANSFERS = "Inventory Stock Transfers";
const TITLE_INVENTORY_VENDORS = "All Vendors";
const TITLE_INVENTORY_VENDORS_ADD = "New Vendor";
const TITLE_INVENTORY_VENDORS_DETAILS = "Vendor Details";
const TITLE_INVENTORY_ADJUSTMENTS = "Inventory Adjustments";
const TITLE_INVENTORY_FACTORIES = "All Factories";
const TITLE_INVENTORY_FACTORIES_ADD = "New Factory";
const TITLE_INVENTORY_FACTORIES_DETAILS = "Factory Details";
const TITLE_CRM_CUSTOMERS = "All Customers";
const TITLE_CRM_CUSTOMERS_ADD = "New Customer";
const TITLE_CRM_CUSTOMERS_DETAILS = "Customer Details";
const TITLE_CRM_DASHBOARD = "CRM Dashboard";
const TITLE_CRM_INVOICES = "All Invoices";
const TITLE_CRM_INVOICES_ADD = "New Invoice";
const TITLE_CRM_INVOICES_DETAILS = "Invoice Details";
const TITLE_CRM_LEADS = "CRM Leads";
const TITLE_CRM_MARKETING = "CRM Marketing";
const TITLE_CRM_OPPORTUNITIES = "CRM Opportunities";
const TITLE_CRM_QUOTES = "All Quotes";
const TITLE_CRM_QUOTES_ADD = "New Quote";
const TITLE_CRM_QUOTES_DETAILS = "Quote Details";
const TITLE_CRM_ORDERS = "All Orders";
const TITLE_CRM_ORDERS_ADD = "New Order";
const TITLE_CRM_ORDERS_DETAILS = "Order Details";
const TITLE_CRM_REPORTS = "CRM Reports";
const TITLE_CRM_SALES = "CRM Sales";
const TITLE_CRM_ARTWORK = "CRM Artwork";
const TITLE_CRM_SHIPPING = "All Shipments";
const TITLE_CRM_SHIPPING_ADD = "New Shipping";
const TITLE_CRM_SHIPPING_DETAILS = "Shipping Details";
const TITLE_ADMIN_ACTIVITY_LOGS = "Admin Activity Logs";
const TITLE_ADMIN_ANALYTICS = "Admin Analytics";
const TITLE_ADMIN_BACKUPS = "Admin Backups";
const TITLE_ADMIN_DASHBOARD = "Admin Dashboard";
const TITLE_ADMIN_DEPARTMENTS = "Admin Departments";
const TITLE_ADMIN_INTEGRATIONS = "Admin Integrations";
const TITLE_ADMIN_ROLES_PERMISSION = "Admin Roles Permissions";
const TITLE_ADMIN_SYSTEM_SETTINGS = "Admin System Settings";
const TITLE_ADMIN_USER_MANAGEMENT = "Admin User Management";
const TITLE_PRODUCTION_ORDERS = "Production Orders";

export {
  TITLE_DASHBOARD,
  TITLE_CATEGORY,
  TITLE_SHIPPING,
  TITLE_STOCK,
  TITLE_SUPPLIER,
  TITLE_PROFILE,
  TITLE_BILLING,
  TITLE_SETTINGS,
  TITLE_EMAIL_NOTIFICATION,
  TITLE_SHIPPING_PRESETS,
  TITLE_INVENTORY_PRODUCTS,
  TITLE_INVENTORY_STOCK,
  TITLE_INVENTORY_ORDERS,
  TITLE_INVENTORY_ORDERS_ADD,
  TITLE_INVENTORY_ORDERS_DETAILS,
  TITLE_INVENTORY_SUPPLIERS,
  TITLE_INVENTORY_PURCHASE_ORDERS,
  TITLE_INVENTORY_PURCHASE_ORDERS_ADD,
  TITLE_INVENTORY_PURCHASE_ORDERS_DETAILS,
  TITLE_INVENTORY_TRANSFERS,
  TITLE_INVENTORY_ADJUSTMENTS,
  TITLE_INVENTORY_VENDORS,
  TITLE_INVENTORY_VENDORS_ADD,
  TITLE_INVENTORY_VENDORS_DETAILS,
  TITLE_INVENTORY_FACTORIES,
  TITLE_INVENTORY_FACTORIES_ADD,
  TITLE_INVENTORY_FACTORIES_DETAILS,
  TITLE_CRM_CUSTOMERS,
  TITLE_CRM_CUSTOMERS_ADD,
  TITLE_CRM_CUSTOMERS_DETAILS,
  TITLE_CRM_DASHBOARD,
  TITLE_CRM_INVOICES,
  TITLE_CRM_INVOICES_ADD,
  TITLE_CRM_INVOICES_DETAILS,
  TITLE_CRM_LEADS,
  TITLE_CRM_MARKETING,
  TITLE_CRM_OPPORTUNITIES,
  TITLE_CRM_QUOTES,
  TITLE_CRM_QUOTES_ADD,
  TITLE_CRM_QUOTES_DETAILS,
  TITLE_CRM_ORDERS,
  TITLE_CRM_ORDERS_ADD,
  TITLE_CRM_ORDERS_DETAILS,
  TITLE_CRM_REPORTS,
  TITLE_CRM_SALES,
  TITLE_CRM_ARTWORK,
  TITLE_CRM_SHIPPING,
  TITLE_CRM_SHIPPING_ADD,
  TITLE_CRM_SHIPPING_DETAILS,
  TITLE_ADMIN_ACTIVITY_LOGS,
  TITLE_ADMIN_ANALYTICS,
  TITLE_ADMIN_BACKUPS,
  TITLE_ADMIN_DASHBOARD,
  TITLE_ADMIN_DEPARTMENTS,
  TITLE_ADMIN_INTEGRATIONS,
  TITLE_ADMIN_ROLES_PERMISSION,
  TITLE_ADMIN_SYSTEM_SETTINGS,
  TITLE_ADMIN_USER_MANAGEMENT,
  TITLE_PRODUCTION_ORDERS,
};
