const PAGE_LOGIN_URL = '/login';
const PAGE_DASHBOARD_URL = '/dashboard';
const PAGE_DASHBOARD_CUSTOMERS_URL = `${PAGE_DASHBOARD_URL}/customers`;
const PAGE_DASHBOARD_SALES_URL = `${PAGE_DASHBOARD_URL}/sales`;
const PAGE_DASHBOARD_ANALYTICS_URL = `${PAGE_DASHBOARD_URL}/analytics`;
const PAGE_DASHBOARD_LEADS_URL = `${PAGE_DASHBOARD_URL}/leads`;
const PAGE_DASHBOARD_INVOICES_URL = `${PAGE_DASHBOARD_URL}/invoices`;
const PAGE_DASHBOARD_MESSAGES_URL = `${PAGE_DASHBOARD_URL}/messages`;
const PAGE_DASHBOARD_EMAIL_URL = `${PAGE_DASHBOARD_URL}/email`;
const PAGE_DASHBOARD_PRODUCTS_URL = `${PAGE_DASHBOARD_URL}/products`;
const PAGE_DASHBOARD_BILLING_URL = `${PAGE_DASHBOARD_URL}/billing`;
const PAGE_DASHBOARD_SETTINGS_URL = `${PAGE_DASHBOARD_URL}/settings`;

export {
    PAGE_LOGIN_URL,
    PAGE_DASHBOARD_URL,
    PAGE_DASHBOARD_CUSTOMERS_URL,
    PAGE_DASHBOARD_SALES_URL,
    PAGE_DASHBOARD_ANALYTICS_URL,
    PAGE_DASHBOARD_LEADS_URL,
    PAGE_DASHBOARD_INVOICES_URL,
    PAGE_DASHBOARD_MESSAGES_URL,
    PAGE_DASHBOARD_EMAIL_URL,
    PAGE_DASHBOARD_PRODUCTS_URL,
    PAGE_DASHBOARD_BILLING_URL,
    PAGE_DASHBOARD_SETTINGS_URL
}
