const PAGE_DASHBOARD_URL = "/dashboard";
const PAGE_CATEGORY_URL = "/category";
const PAGE_SHIPPING_URL = "/shipping";
const PAGE_STOCK_URL = "/stock";
const PAGE_SUPPLIER_URL = "/supplier";
const PAGE_PRODUCTION_URL = "/production";
const PAGE_PROFILE_URL = "/profile";
const PAGE_BILLING_URL = "/billing";
const PAGE_SETTINGS_URL = "/settings";
const PAGE_EMAIL_NOTIFICATION_URL = "/email-notification";
const PAGE_SHIPPING_PRESETS_URL = "/settings/shipping-presets";
const PAGE_PRODUCTION_PRODUCTS_URL = `${PAGE_PRODUCTION_URL}/products`;
const PAGE_PRODUCTION_SUPPLIERS_URL = `${PAGE_PRODUCTION_URL}/suppliers`;
const PAGE_PRODUCTION_VENDORS_URL = `${PAGE_PRODUCTION_URL}/vendors`;
const PAGE_PRODUCTION_PURCHASE_ORDERS_URL = `${PAGE_PRODUCTION_URL}/purchase-orders`;
const PAGE_PRODUCTION_ORDERS_URL = `${PAGE_PRODUCTION_URL}/production-orders`;
const PAGE_PRODUCTION_FACTORIES_URL = `${PAGE_PRODUCTION_URL}/factories`;
const PAGE_CRM_URL = "/crm";
const PAGE_CRM_DASHBOARD_URL = `${PAGE_CRM_URL}/dashboard`;
const PAGE_CRM_CUSTOMERS_URL = `${PAGE_CRM_URL}/customers`;
const PAGE_CRM_ARTWORK_URL = `${PAGE_CRM_URL}/artwork`;
const PAGE_CRM_LEADS_URL = `${PAGE_CRM_URL}/leads`;
const PAGE_CRM_OPPORTUNITIES_URL = `${PAGE_CRM_URL}/opportunities`;
const PAGE_CRM_SALES_URL = `${PAGE_CRM_URL}/sales`;
const PAGE_CRM_QUOTES_URL = `${PAGE_CRM_URL}/quotes`;
const PAGE_CRM_ORDERS_URL = `${PAGE_CRM_URL}/orders`;
const PAGE_CRM_SHIPPING_URL = `${PAGE_CRM_URL}/shipping`;
const PAGE_CRM_INVOICES_URL = `${PAGE_CRM_URL}/invoices`;
const PAGE_CRM_MARKETING_URL = `${PAGE_CRM_URL}/marketing`;
const PAGE_CRM_PAYMENT_URL = `${PAGE_CRM_URL}/payment`;
const PAGE_CRM_REPORTS_URL = `${PAGE_CRM_URL}/reports`;
const PAGE_ADMIN_URL = "/admin";
const PAGE_ADMIN_ACTIVITY_LOGS_URL = `${PAGE_ADMIN_URL}/activity-logs`;
const PAGE_ADMIN_ANALYTICS_URL = `${PAGE_ADMIN_URL}/analytics`;
const PAGE_ADMIN_BACKUPS_URL = `${PAGE_ADMIN_URL}/backups`;
const PAGE_ADMIN_DASHBOARD_URL = `${PAGE_ADMIN_URL}/dashboard`;
const PAGE_ADMIN_DEPARTMENTS_URL = `${PAGE_ADMIN_URL}/departments`;
const PAGE_ADMIN_INTEGRATIONS_URL = `${PAGE_ADMIN_URL}/integrations`;
const PAGE_ADMIN_ROLES_PERMISSION_URL = `${PAGE_ADMIN_URL}/roles-permission`;
const PAGE_ADMIN_SYSTEM_SETTINGS_URL = `${PAGE_ADMIN_URL}/system-settings`;
const PAGE_ADMIN_USER_MANAGEMENT_URL = `${PAGE_ADMIN_URL}/user-management`;

export {
  PAGE_DASHBOARD_URL,
  PAGE_CATEGORY_URL,
  PAGE_SHIPPING_URL,
  PAGE_STOCK_URL,
  PAGE_SUPPLIER_URL,
  PAGE_PROFILE_URL,
  PAGE_BILLING_URL,
  PAGE_SETTINGS_URL,
  PAGE_EMAIL_NOTIFICATION_URL,
  PAGE_SHIPPING_PRESETS_URL,
  PAGE_PRODUCTION_URL,
  PAGE_PRODUCTION_PRODUCTS_URL,
  PAGE_PRODUCTION_SUPPLIERS_URL,
  PAGE_PRODUCTION_VENDORS_URL,
  PAGE_PRODUCTION_PURCHASE_ORDERS_URL,
  PAGE_PRODUCTION_ORDERS_URL,
  PAGE_PRODUCTION_FACTORIES_URL,
  PAGE_CRM_URL,
  PAGE_CRM_DASHBOARD_URL,
  PAGE_CRM_CUSTOMERS_URL,
  PAGE_CRM_ARTWORK_URL,
  PAGE_CRM_LEADS_URL,
  PAGE_CRM_OPPORTUNITIES_URL,
  PAGE_CRM_SALES_URL,
  PAGE_CRM_QUOTES_URL,
  PAGE_CRM_ORDERS_URL,
  PAGE_CRM_SHIPPING_URL,
  PAGE_CRM_INVOICES_URL,
  PAGE_CRM_MARKETING_URL,
  PAGE_CRM_PAYMENT_URL,
  PAGE_CRM_REPORTS_URL,
  PAGE_ADMIN_URL,
  PAGE_ADMIN_ACTIVITY_LOGS_URL,
  PAGE_ADMIN_ANALYTICS_URL,
  PAGE_ADMIN_BACKUPS_URL,
  PAGE_ADMIN_DASHBOARD_URL,
  PAGE_ADMIN_DEPARTMENTS_URL,
  PAGE_ADMIN_INTEGRATIONS_URL,
  PAGE_ADMIN_ROLES_PERMISSION_URL,
  PAGE_ADMIN_SYSTEM_SETTINGS_URL,
  PAGE_ADMIN_USER_MANAGEMENT_URL,
};
