const SIDEBAR_TITLE_OVERVIEW = "Overview";
const SIDEBAR_TITLE_CUSTOMERS = "Customers";
const SIDEBAR_TITLE_SALES = "Sales";
const SIDEBAR_TITLE_ANALYTICS = "Analytics";

export {
    SIDEBAR_TITLE_OVERVIEW,
    SIDEBAR_TITLE_CUSTOMERS,
    SIDEBAR_TITLE_SALES,
    SIDEBAR_TITLE_ANALYTICS
}
